# Generated by Django 6.0.4 on 2026-05-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/heroes/')),
                ('sub_headline', models.CharField(blank=True, max_length=300, null=True)),
                ('body_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
