# Generated by Django 6.0.4 on 2026-05-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_pagecontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'verbose_name_plural': 'Page Contents'},
        ),
    ]
