# Generated by Django 6.0.4 on 2026-05-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_pagecontent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='featured_products',
            field=models.ManyToManyField(blank=True, help_text='Select products to display on this page. Use this for Best Sellers, New Products, Offers, Combos, etc.', related_name='featured_on_pages', to='shop.product'),
        ),
    ]
