# Generated by Django 6.0.4 on 2026-05-11 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Main cover image shown in the article listing card.', null=True, upload_to='articles/featured/')),
                ('summary', models.TextField(blank=True, help_text='Short summary shown on the page listing. 1-2 sentences.', max_length=500, null=True)),
                ('published_date', models.DateField(blank=True, help_text='Date this article was published. Leave blank for draft.', null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = appears first on the page.')),
                ('page', models.ForeignKey(help_text='The page this article belongs to (e.g. Mushroom Benefits, Recipes, Foraging Guides, Our Story).', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='shop.pagecontent')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['order', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('heading', '📝 Heading'), ('paragraph', '📄 Paragraph'), ('image', '🖼️ Image'), ('video', '🎬 Video (YouTube/Vimeo URL)'), ('quote', '💬 Quote / Callout'), ('divider', '➖ Divider')], default='paragraph', max_length=20)),
                ('text_content', models.TextField(blank=True, help_text='Text for heading, paragraph, or quote blocks.', null=True)),
                ('image', models.ImageField(blank=True, help_text='Image for image blocks. Use high-quality photos.', null=True, upload_to='articles/content/')),
                ('image_caption', models.CharField(blank=True, help_text='Optional caption displayed below the image.', max_length=300, null=True)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo embed URL (e.g. https://www.youtube.com/embed/VIDEO_ID).', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the article. Lower = appears first.')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='shop.article')),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
                'ordering': ['order'],
            },
        ),
    ]
