# Generated by Django 6.0.4 on 2026-05-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_article_contentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='The main blog content. You can add paragraphs, images, and videos here using the rich text editor.', null=True),
        ),
    ]
