# Generated by Django 6.0.4 on 2026-05-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverArticle',
            fields=[
            ],
            options={
                'verbose_name': 'Story / Article',
                'verbose_name_plural': 'Stories & Articles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.article',),
        ),
        migrations.CreateModel(
            name='DiscoverPage',
            fields=[
            ],
            options={
                'verbose_name': 'Discover Page',
                'verbose_name_plural': 'Discover Pages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.pagecontent',),
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.category',),
        ),
        migrations.CreateModel(
            name='ShopPage',
            fields=[
            ],
            options={
                'verbose_name': 'Shop Page',
                'verbose_name_plural': 'Shop Pages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.pagecontent',),
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='UtilityContact',
            fields=[
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.contactmessage',),
        ),
        migrations.CreateModel(
            name='UtilityPage',
            fields=[
            ],
            options={
                'verbose_name': 'Utility Page',
                'verbose_name_plural': 'Utility Pages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.pagecontent',),
        ),
        migrations.CreateModel(
            name='ValuePage',
            fields=[
            ],
            options={
                'verbose_name': 'Value Page',
                'verbose_name_plural': 'Value Pages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.pagecontent',),
        ),
        migrations.AlterModelOptions(
            name='contentblock',
            options={'verbose_name': 'Content Block', 'verbose_name_plural': 'Content Blocks'},
        ),
    ]
